### ISSUE TITLE
Отладка v2.transition

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder#312]
Опубликована сборка Заказа дилера с движком v2.transition

### Зачем это надо
- Чтобы обеспечить стабильное и предсказуемое поведение системы
- Чтобы привести код приложения в соответствие со стандартами современной веб-разработки
- Чтобы обрести фундамент, на котором не страшно строить большую систему (v0.12 таковым не является)
- Чтобы иметь одинаковую кодовую базу как для клиентской, так и для серверной части системы

### Особенности
- Движок данных - полноценный v2
- Интерфейс - старый v0.12, который выполняется в контейнерах React
- По аналогии с платформой 1С, v2.transition - это управляемое приложение, в котором работают старые формы толстого клиента
- Код самого Заказа дилера почти не поменялся, но изменилось окружение, в котором этот код выполняется, что с высокой вероятностью сломает работу ряда механизмов
- Отладка еще не закончена, у меня есть внутренний список ошибок, но предлагаю всем подключиться к тестированию и регистрировать найденные ошибки в этой ветке

База Арибаз v2 доступна по адресу: https://aribaz.oknosoft.ru/
Логины - пароли - суффиксы - те же, что и в 0.12.
База CouchDB - общая, изменения сделанные в v2 видны в v0.12 и наоборот.

**Comment by Sehktel** [comment]
@unpete 
первая - metadata.transition.js:4556 Uncaught SyntaxError: Unexpected token )
```js
            const try_auth = [];
            if (!_paths.user_node) {
              md.bases().forEach((name) => {
                if (t.remote[name]) {
                  try_auth.push(
                    _paths.user_node ? this.remote[name].info() : this.remote[name].login(username, password),
                  );
                }
              });
            }
````

**Comment by unpete** [comment]
@Sehktel браузер, наверное IE3 или NetscapeNavigator образца 1996 года?

**Comment by Sehktel** [comment]
Хм ... 

Opera  : 46.0.2597.57 Ubuntu 16.04.2 LTS (x86_64; Unity)   Открыл.

Mozilla FF 54.0 (64-bit) Linux - открыл.

Chromium Version 59.0.3071.109 (Developer Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)  
Открыл

Chrome Версия 60.0.3112.90 (Официальная сборка), (32 бит)  Windows 7-32bit Открыл.

Chrome Version 56.0.2924.87 (64-bit) Ubuntu Linux - начал открывать окно авторизации.

По всей видимости кодовая база младше  57 дает подобные ошибки.


```js 
  get dimension_bounds() {
    let bounds = super.dimension_bounds;
    const ib = this.l_visualization._by_insets.bounds;
    if (ib.height && ib.bottom > bounds.bottom) {
      const delta = ib.bottom - bounds.bottom + 10;
      bounds = bounds.unite(
        new paper.Rectangle(bounds.bottomLeft, bounds.bottomRight.add([0, delta < 250 ? delta * 1.1 : delta * 1.2])),
      );
    }
    return bounds;
  }
```
```js 
new paper.Rectangle(bounds.bottomLeft, bounds.bottomRight.add([0, delta < 250 ? delta * 1.1 : delta * 1.2])),
      );
```

windowbuilder.js:3378 Uncaught SyntaxError: Unexpected token )  
Тоже наверно на запятую.

**Comment by Sehktel** [comment]
Открываю в Chromium Version 59.0.3071.109 (Developer Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit) 

Зашел, создал заказ, рассчитал спецификацию.
Захожу во вкладку спецификации, хочу отсортировать по номенклатуре. 
```js
metadata.transition.js:339 Uncaught ReferenceError: has_dot is not defined
    at TabularSection.sort (https://eco.oknosoft.ru/dist/metadata.transition.js:339:4)
    at window.(anonymous function).<anonymous> (https://eco.oknosoft.ru/dist/metadata.transition.js:11487:9)
    at window.(anonymous function).obj.callEvent (https://eco.oknosoft.ru/dist/dhtmlx_debug.js:984:35)
    at HTMLTableElement._onHeaderClick (https://eco.oknosoft.ru/dist/dhtmlx_debug.js:20835:20)
```
Код:
```js
	sort(fields) {
		if (typeof fields == "string"){
			fields = fields.split(",");
		}
		let sql = "select * from ? order by ",
			res = true;
			has_dot;
		for(let f of fields){
      has_dot = has_dot || f.match('.');
      f = f.trim().replace(/\s{1,}/g, " ").split(" ");
      if (res){
        res = false;
      }
      else{
        sql += ", ";
      }
      sql += "`" + f[0] + "`";
      if (f[1]){
        sql += " " + f[1];
      }
    }
```

Конкретно: 
```js 
		let sql = "select * from ? order by ",
			res = true;
			has_dot;
```
Точка с запятой -> запятая

**Comment by unpete** [comment]
> Точка с запятой -> запятая

Спасибо, поправил.
Кешем я пока не управляю - очистку кеша и аппаратную перезагрузку страницы делайте самостоятельно.

**Comment by Sehktel** [comment]
В результате изменения формулы определения цвета, получение цвета, например при расчете ламинации, изменило свое поведение.
Если раньше это было
```js
const {is_in, is_out} = clr.sides;
```
То теперь это 
```js
const {is_in, is_out} = clr.sides();
```
За остальным формула ламинации должна работать.  
Соотв. при смене версий надо будет учесть данный момент.

**Comment by unpete** [comment]
Думаю, надо сделать как раньше. Sides, задумана, как свойство, а не как
метод.

**Comment by Felishia** [comment]
@unpete , я тоже зашла. Остаются картинки, даже после удаления и перезаписи заказа. 
![image](https://user-images.githubusercontent.com/24691533/28973951-6b49e552-793d-11e7-9364-707b12a171fd.png)

**Comment by Felishia** [comment]
Выделила 2 стеклопакета в изделии, зашла на закладку - свойства элемента, нажала кнопку состав заполнения в элемент, добавила тонировочную пленку. Нажимаю закрыть (через х) на рисунке формула обновляется, но меню не закрывается


```js
windowbuilder.js:2411 Uncaught ReferenceError: update is not defined
    at GlassInserts.onclose (windowbuilder.js:2411)
    at dhtmlXWindowsCell.obj.callEvent (dhtmlx_debug.js:984)
    at dhtmlXWindowsCell._callMainEvent (dhtmlx_debug.js:45813)
    at dhtmlXWindows._callMainEvent (dhtmlx_debug.js:45686)
    at dhtmlXWindows._winClose (dhtmlx_debug.js:45412)
    at dhtmlXWindows._winButtonClick (dhtmlx_debug.js:46295)
    at dhtmlXWindows._winMouseDownHandler (dhtmlx_debug.js:45574)
    at dhtmlXWindows.obj.callEvent (dhtmlx_debug.js:984)
    at HTMLDivElement._winOnMouseDown (dhtmlx_debug.js:44804)
```

```js
  onclose() {
    const {grids} = this.wnd.elmnts;
    const {elm} = this;
    grids.inserts && grids.inserts.editStop();
    elm.project.register_change(true);
    elm.project.notify(elm, update, {inset: true});
    return true;
  }
```

**Comment by unpete** [comment]
> картинки, даже после удаления и перезаписи заказа

Это не совсем ошибка. Компонент миниэскизов не закончен

> формула обновляется, но меню не закрывается

Спасибо, учту

**Comment by unpete** [comment]
> кнопка состав заполнения

Исправил

**Comment by Sehktel** [comment]
Рассчитал заказ, выбрал в спецификации номенклатуру.

![selection_049](https://user-images.githubusercontent.com/24711055/29073749-71a2356a-7c55-11e7-96d8-83e5d57ad139.png)

Выбираю undefind (Формула), говорю показать все. 
Возникает ошибка  metadata.transition.js:9817
```js
metadata.transition.js:9817 Uncaught TypeError: Cannot read property 'then' of undefined
    at CatManager.DataManager.sync_grid (metadata.transition.js:9817)
    at metadata.transition.js:10385
```
Код:
```js
		function to_grid(res) {
			return new Promise(function (resolve, reject) {
				if (typeof res == 'string') {
					if (res.substr(0, 1) == '{')
						res = JSON.parse(res);
					if (grid && grid.parse) {
						grid.xmlFileUrl = 'exec';
						grid.parse(res, function () {
							resolve(res);
						}, 'xml');
					} else
						resolve(res);
				} else if (grid instanceof dhtmlXTreeView && grid.loadStruct) {
					grid.loadStruct(res, function () {
						resolve(res);
					});
				} else
					resolve(res);
			});
		}
		return request()
			.then(to_grid)  //  жалуется на данную строку
			.catch(record_log);
	};
```

![selection_050](https://user-images.githubusercontent.com/24711055/29073763-853f5af8-7c55-11e7-96be-994b37d81804.png)
Появляется пустое окно.

При попытке закрыть через esc:
metadata.transition.js:9616
```js
metadata.transition.js:9616 Uncaught TypeError: Cannot read property 'getTopmostWindow' of undefined
    at metadata.transition.js:9616
    at dhtmlXWindows.forEachWindow (dhtmlx_debug.js:44883)
    at InterfaceObjs.check_exit (metadata.transition.js:9615)
    at HTMLBodyElement.body_keydown (metadata.transition.js:12609)
```

**Comment by Sehktel** [comment]
Где-то отвалилось.  Не критично, но предупреждение
```js
DevTools failed to parse SourceMap: https://eco.oknosoft.ru/dist/metadata.transition.js.map
```

**Comment by Sehktel** [comment]
Сейчас в интерфейсе есть неотлаженные Доп.вставки в изделие, Доп.вставки в элемент. 
Сейчас мы вроде бы обходимся без них. Поэтому предлагаю их скрыть, чтобы не вызывать лишних вопросов у менеджеров.
![selection_055](https://user-images.githubusercontent.com/24711055/29171491-670cdd8a-7de5-11e7-9baf-3a85812b32de.png)
![selection_056](https://user-images.githubusercontent.com/24711055/29171490-6701cf08-7de5-11e7-8698-9fdcdbfa9729.png)

**Comment by Sehktel** [comment]
Не могу создавать заказы. 
при создании заказа и вызова формулы изменения номера договора:
```js
const proto = $p.DocCalc_order.prototype;
delete proto.new_number_doc;
Object.defineProperty(proto, 'new_number_doc', {
  value: function (prefix) {    
    prefix = ($p.current_user.suffix || '000');
    while(prefix.length < 4){
      prefix = '0' + prefix;
    };
    prefix += ($p.current_user.prefix || 'XX').substr(0,2);
    $p.DataObj.prototype.new_number_doc.call(this, prefix);
  }
});
```
```js
 $p.DataObj
undefined


 $p.DataObj.prototype
VM219:1 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at eval (eval at value (eval at value (wnd_debug.js:1200)), <anonymous>:1:12)
    at DocCalc_order.value (eval at value (wnd_debug.js:1200), <anonymous>:12:5)
    at DocCalc_order.value_change (wnd_debug.js:4740)
    at DocCalc_order.__setter (metadata.transition.js:586)
    at DocCalc_order._setter (metadata.transition.js:651)
    at DocCalc_order.set organization [as organization] (init.js:2545)
    at TabularSection.acl_objs.find_rows (wnd_debug.js:4633)
    at TabularSection.callback (metadata.transition.js:287)
    at TabularSection._find_rows (metadata.transition.js:5841)
    at TabularSection.find_rows (metadata.transition.js:289)
```

**Comment by unpete** [comment]
> при создании заказа и вызова формулы изменения номера договора

Доработал модификатор, чтобы он вёл себя одинаково в v2 и v0.12.
Номер документа пересчитывается при создании, при изменении организации или года в дате документа. Здесь я не оригинален - см. код типовых конфигураций 1С.

**Comment by unpete** [comment]
> есть неотлаженные Доп.вставки в изделие

Неотлаженные кем?
Арибаз вставки в изделие использует. С высокой вероятностью и вы захотите.

**Comment by Sehktel** [comment]
> Арибаз вставки в изделие использует. С высокой вероятностью и вы захотите.

Значит я просто не знаю об их функционале.

**Comment by Sehktel** [comment]
Не могу нарисовать изделие с нуля.
Заказ - Добавить из построителя - закрываю диалог выбора шаблонов.
Инструмент "Добавить профиль" - попытка нарисовать профиль - ошибка.
```js
  hitTest(event) {

    this.addl_hit = null;
    this.hitItem = null;

    if(this.profile.elm_type == $p.enm.elm_types.Добор){
      this.hitTest_addl(event);
    }
    else if(this.profile.elm_type == $p.enm.elm_types.Соединитель){
      this.hitTest_connective(event);
    }
```

Ошибка в строке 
```js
if(this.profile.elm_type == $p.enm.elm_types.Добор){
```

```js
Uncaught TypeError: Cannot read property 'elm_type' of undefined
    at ToolPen.hitTest (https://eco.oknosoft.ru/dist/windowbuilder.js:12118:20)
    at ToolPen.on_mousemove (https://eco.oknosoft.ru/dist/windowbuilder.js:11776:10)
    at ToolPen.emit (https://cdn.jsdelivr.net/combine/gh/moment/moment@2.18/min/moment.min.js,gh/moment/moment@2.18/locale/ru.min.js,gh/agershun/alasql@0.4.1/dist/alasql.min.js,gh/pouchdb/pouchdb@6.3.4/dist/pouchdb.min.js,gh/pouchdb/pouchdb@6.3.4/dist/pouchdb.find.min.js,gh/nolanlawson/pouchdb-authentication@v0.5.5/dist/pouchdb.authentication.min.js,gh/paperjs/paper.js@v0.11.4/dist/paper-core.min.js,gh/flitbit/diff@v0.3.8/releases/deep-diff-0.3.8.min.js:73:8371)
    at s (https://cdn.jsdelivr.net/combine/gh/moment/moment@2.18/min/moment.min.js,gh/moment/moment@2.18/locale/ru.min.js,gh/agershun/alasql@0.4.1/dist/alasql.min.js,gh/pouchdb/pouchdb@6.3.4/dist/pouchdb.min.js,gh/pouchdb/pouchdb@6.3.4/dist/pouchdb.find.min.js,gh/nolanlawson/pouchdb-authentication@v0.5.5/dist/pouchdb.authentication.min.js,gh/paperjs/paper.js@v0.11.4/dist/paper-core.min.js,gh/flitbit/diff@v0.3.8/releases/deep-diff-0.3.8.min.js:73:181865)
    at ToolPen._handleMouseEvent (https://cdn.jsdelivr.net/combine/gh/moment/moment@2.18/min/moment.min.js,gh/moment/moment@2.18/locale/ru.min.js,gh/agershun/alasql@0.4.1/dist/alasql.min.js,gh/pouchdb/pouchdb@6.3.4/dist/pouchdb.min.js,gh/pouchdb/pouchdb@6.3.4/dist/pouchdb.find.min.js,gh/nolanlawson/pouchdb-authentication@v0.5.5/dist/pouchdb.authentication.min.js,gh/paperjs/paper.js@v0.11.4/dist/paper-core.min.js,gh/flitbit/diff@v0.3.8/releases/deep-diff-0.3.8.min.js:73:182109)
    at initialize._handleMouseEvent (https://cdn.jsdelivr.net/combine/gh/moment/moment@2.18/min/moment.min.js,gh/moment/moment@2.18/locale/ru.min.js,gh/agershun/alasql@0.4.1/dist/alasql.min.js,gh/pouchdb/pouchdb@6.3.4/dist/pouchdb.min.js,gh/pouchdb/pouchdb@6.3.4/dist/pouchdb.find.min.js,gh/nolanlawson/pouchdb-authentication@v0.5.5/dist/pouchdb.authentication.min.js,gh/paperjs/paper.js@v0.11.4/dist/paper-core.min.js,gh/flitbit/diff@v0.3.8/releases/deep-diff-0.3.8.min.js:73:175004)
    at r (https://cdn.jsdelivr.net/combine/gh/moment/moment@2.18/min/moment.min.js,gh/moment/moment@2.18/locale/ru.min.js,gh/agershun/alasql@0.4.1/dist/alasql.min.js,gh/pouchdb/pouchdb@6.3.4/dist/pouchdb.min.js,gh/pouchdb/pouchdb@6.3.4/dist/pouchdb.find.min.js,gh/nolanlawson/pouchdb-authentication@v0.5.5/dist/pouchdb.authentication.min.js,gh/paperjs/paper.js@v0.11.4/dist/paper-core.min.js,gh/flitbit/diff@v0.3.8/releases/deep-diff-0.3.8.min.js:73:172364)
    at HTMLDocument.v.(anonymous function) (https://cdn.jsdelivr.net/combine/gh/moment/moment@2.18/min/moment.min.js,gh/moment/moment@2.18/locale/ru.min.js,gh/agershun/alasql@0.4.1/dist/alasql.min.js,gh/pouchdb/pouchdb@6.3.4/dist/pouchdb.min.js,gh/pouchdb/pouchdb@6.3.4/dist/pouchdb.find.min.js,gh/nolanlawson/pouchdb-authentication@v0.5.5/dist/pouchdb.authentication.min.js,gh/paperjs/paper.js@v0.11.4/dist/paper-core.min.js,gh/flitbit/diff@v0.3.8/releases/deep-diff-0.3.8.min.js:73:173697)
```
